# Generated by Django 5.1.1 on 2024-09-23 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='dataCompra',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='quantidadeProdutos',
            field=models.IntegerField(),
        ),
    ]
